// Imports
import { expect } from "@libs/testing"
import { ddl } from "./_ddl.ts"
import * as is from "./schema.ts"
import { Status } from "../fixtures/test_schema/models.ts"
import { Type } from "../database.ts"

for (const type of [Type.SQLite, Type.PostgreSQL]) {
  Deno.test(`${Type[type]} DDL preserves database constraints without application validators`, () => {
    const table = is.table('odd"table', {
      id: is.int().primary({ identity: true }),
      parent: is.int().optional().references("parent", "id", { delete: "null", update: "cascade" }),
      email: is.string().regex(/@/).unique(),
      enabled: is.boolean().default(true).index(),
      value: is.number(),
      counter: is.bigint(),
      date: is.date(),
      time: is.timestamp(),
      empty: is.null(),
      data: is.object({ value: is.string() }),
    }).index(["date", "enabled"])
    const statements = ddl(table, type)
    expect(statements).toHaveLength(4)
    expect(statements[0]).toContain('CREATE TABLE IF NOT EXISTS "odd""table"')
    expect(statements[0]).toContain('REFERENCES "parent" ("id") ON DELETE SET NULL ON UPDATE CASCADE')
    expect(statements[0]).toContain('"counter" BIGINT NOT NULL')
    expect(statements[0]).not.toContain(" CHECK ")
    expect(statements[0]).not.toContain(" DEFAULT TRUE")
    expect(statements[0]).not.toContain("/@/")
    expect(statements[0]).toContain(type === Type.SQLite ? "AUTOINCREMENT" : "GENERATED BY DEFAULT AS IDENTITY")
    expect(statements[0]).toContain(type === Type.SQLite ? '"enabled" INTEGER NOT NULL' : '"enabled" BOOLEAN NOT NULL')
    expect(statements[0]).toContain(type === Type.SQLite ? '"data" TEXT NOT NULL' : '"data" JSONB NOT NULL')
    expect(statements[0]).toContain(type === Type.SQLite ? '"date" TEXT NOT NULL' : '"date" TIMESTAMPTZ NOT NULL')
    expect(statements[0]).toContain(type === Type.SQLite ? '"time" INTEGER NOT NULL' : '"time" BIGINT NOT NULL')
    expect(statements[2]).toContain("CREATE UNIQUE INDEX")
  })
}

for (
  const { name, schema } of [
    { name: "object without table declaration", schema: is.object({ id: is.int() }) },
    { name: "empty table", schema: is.table("empty", {}) },
    { name: "composite identity", schema: is.table("keys", { first: is.int().primary({ identity: true }), second: is.int().primary() }) },
    { name: "mixed primary declarations", schema: is.table("keys", { first: is.int().primary(), second: is.int() }).primary(["first", "second"]) },
    { name: "empty primary columns", schema: is.table("keys", { id: is.int() }).primary([]) },
    { name: "duplicate primary columns", schema: is.table("keys", { id: is.int() }).primary(["id", "id"]) },
    { name: "unknown primary column", schema: is.table("keys", { id: is.int() }).primary(["missing" as "id"]) },
    { name: "identity string", schema: is.table("ids", { id: is.string().primary({ identity: true }) }) },
    { name: "nullable primary", schema: is.table("ids", { id: is.int().nullable().primary() }) },
    { name: "null primary", schema: is.table("ids", { id: is.null().primary() }) },
    { name: "null action on required column", schema: is.table("refs", { id: is.int().references("other", "id", { delete: "null" }) }) },
    { name: "table index without columns", schema: is.table("indexes", { id: is.int() }).index() },
    { name: "unknown index column", schema: is.table("indexes", { id: is.int() }).index(["missing" as "id"]) },
    { name: "invalid column identifier", schema: is.table("columns", { "": is.int() }) },
    { name: "invalid reference identifier", schema: is.table("refs", { id: is.int().references("bad\0table", "id") }) },
    { name: "invalid reference action", schema: is.table("refs", { id: is.int().references("parent", "id", { delete: "bad" as "cascade" }) }) },
  ]
) {
  Deno.test(`ddl rejects ${name}`, () => {
    expect(() => ddl(schema, Type.SQLite)).toThrow(TypeError)
  })
}

Deno.test("DDL generation never evaluates default factories", () => {
  const table = is.table("defaults", {
    id: is.string().default(() => {
      throw new Error("must not run")
    }),
  })
  expect(ddl(table, Type.SQLite)).toEqual(['CREATE TABLE IF NOT EXISTS "defaults" ("id" TEXT NOT NULL);'])
})

for (const type of [Type.SQLite, Type.PostgreSQL]) {
  Deno.test(String(Type[type]) + " DDL supports both composite primary declarations", () => {
    const property = is.table("keys", { first: is.int().primary(), second: is.int().optional().primary() })
    const table = is.table("keys", { first: is.int(), second: is.int().optional() }).primary(["first", "second"])
    expect(ddl(property, type)).toEqual(ddl(table, type))
    expect(ddl(table, type)[0]).toContain('"first" INTEGER NOT NULL, "second" INTEGER NOT NULL, PRIMARY KEY ("first", "second")')
  })
  Deno.test(String(Type[type]) + " maps nothing to the SQL NO ACTION referential action", () => {
    const table = is.table("refs", { id: is.int().references("parent", "id", { delete: "nothing", update: "nothing" }) })
    expect(ddl(table, type)[0]).toContain("ON DELETE NO ACTION ON UPDATE NO ACTION")
  })
}

for (const type of [Type.SQLite, Type.PostgreSQL]) {
  Deno.test(`${Type[type]} only stores finite integer enums numerically`, () => {
    const table = is.table("enums", {
      integer: is.enum([0, 1]).optional(),
      native: is.enum(Status),
      string: is.enum(["0", "1"]),
      mixed: is.enum([0, "1"]),
      fraction: is.enum([0.5, 1]),
      infinite: is.enum([Infinity, 1]),
    })
    const [statement] = ddl(table, type)
    expect(statement).toContain('"integer" INTEGER')
    expect(statement).toContain('"native" INTEGER')
    for (const column of ["string", "mixed", "fraction", "infinite"])
      expect(statement).toContain(`"${column}" TEXT`)
  })
}
