// Imports
import { is as z, parse } from "@libs/is"
import { Type } from "../database.ts"
import { metadata } from "./_metadata.ts"
import { storage, unwrap } from "./_codec.ts"

/** Generate table and index creation statements without application validation checks or defaults. */
export function ddl(schema: z.core.$ZodType, type: Type): string[] {
  const options = metadata.get(schema)
  if (!options?.table || schema._zod.def.type !== "object")
    throw new TypeError("DDL generation requires an is.table(name, shape) schema")
  const table = options.table
  const shape = (schema as z.ZodObject).shape
  const columns = Object.entries(shape) as [string, z.core.$ZodType][]
  if (!columns.length)
    throw new TypeError(`Table ${table} must declare at least one column`)
  // Validate table-level options and resolve either form of primary declaration
  const marked = columns.filter(([, value]) => metadata.get(value)?.primary).map(([name]) => name)
  const keys = z.array(z.enum(Object.keys(shape))).min(1).refine((keys) => new Set(keys).size === keys.length, "Columns must be distinct")
  const declaration = parse(
    z.object({
      primary: z.strictObject({ columns: keys }).optional().refine((value) => !value || !marked.length, "Use either table-level or column-level primary declarations"),
      indexes: z.array(z.strictObject({ columns: keys, unique: z.boolean() })).optional(),
    }),
    options,
  )
  const primary = declaration.primary?.columns ?? marked
  const indexes = [...declaration.indexes ?? []]
  const definitions = columns.map(([name, column]) => {
    const kind = storage(column)
    const current = unwrap(column) as z.ZodType
    const integer = kind === "number" && (current._zod.def.type === "enum" || (current as z.ZodNumber).isInt)
    // Validate column options against the resolved storage type and primary-key arity
    const marked = primary.includes(name)
    const action = z.enum(["cascade", "restrict", "nothing", ...(optional(column) && !marked ? ["null"] as const : [])])
    const options = parse(
      z.object({
        primary: (nullable(column) ? z.never({ error: "Primary keys cannot be nullable" }) : z.strictObject({
          identity: (integer && primary.length === 1 ? z.boolean() : z.literal(false, { error: "Identity requires a single integer primary key" })).optional(),
        })).optional(),
        references: z.strictObject({ table: identifier, column: identifier, delete: action.optional(), update: action.optional() }).optional(),
        indexes: z.array(z.strictObject({ unique: z.boolean(), columns: z.undefined().optional() })).optional(),
      }),
      { ...metadata.get(column), primary: marked ? metadata.get(column)?.primary ?? {} : undefined },
    )
    const sql = kind === "timestamp"
      ? (type === Type.SQLite ? "INTEGER" : "BIGINT")
      : kind === "bigint"
      ? "BIGINT"
      : kind === "boolean"
      ? (type === Type.SQLite ? "INTEGER" : "BOOLEAN")
      : kind === "number"
      ? (integer ? "INTEGER" : (type === Type.SQLite ? "REAL" : "DOUBLE PRECISION"))
      : kind === "date"
      ? (type === Type.SQLite ? "TEXT" : "TIMESTAMPTZ")
      : kind === "json"
      ? (type === Type.SQLite ? "TEXT" : "JSONB")
      : "TEXT"
    let definition = `${quote(name)} ${sql}`
    if (options.primary?.identity && type === Type.PostgreSQL)
      definition += " GENERATED BY DEFAULT AS IDENTITY"
    if (options.primary && primary.length === 1)
      definition += " PRIMARY KEY"
    if (options.primary?.identity && type === Type.SQLite)
      definition += " AUTOINCREMENT"
    if (marked || (!optional(column) && kind !== "null"))
      definition += " NOT NULL"
    if (options.references) {
      const reference = options.references
      definition += ` REFERENCES ${quote(reference.table)} (${quote(reference.column)})`
      for (const action of ["delete", "update"] as const) {
        const value = reference[action]
        if (!value)
          continue
        definition += ` ON ${action.toUpperCase()} ${value === "null" ? "SET NULL" : value === "nothing" ? "NO ACTION" : value.toUpperCase()}`
      }
    }
    for (const index of options.indexes ?? [])
      indexes.push({ columns: [name], unique: index.unique })
    return definition
  })
  if (primary.length > 1)
    definitions.push(`PRIMARY KEY (${primary.map(quote).join(", ")})`)
  const statements = [`CREATE TABLE IF NOT EXISTS ${quote(table)} (${definitions.join(", ")});`]
  for (const [index, entry] of indexes.entries()) {
    const name = `${table}_${entry.columns.join("_")}_${index}_${entry.unique ? "unique" : "index"}`
    statements.push(`CREATE ${entry.unique ? "UNIQUE " : ""}INDEX IF NOT EXISTS ${quote(name)} ON ${quote(table)} (${entry.columns.map(quote).join(", ")});`)
  }
  return statements
}

/** Quote an SQL identifier without treating it as an expression. */
function quote(value: string): string {
  parse(identifier, value)
  return `"${value.replaceAll('"', '""')}"`
}

/** Detect explicit nullability without invoking schema defaults. */
function nullable(schema: z.core.$ZodType): boolean {
  const definition = schema._zod.def as { type: string; innerType?: z.core.$ZodType }
  return definition.type === "nullable" || definition.type === "null" || Boolean(definition.innerType && nullable(definition.innerType))
}

/** Detect SQL columns that must accept missing application values. */
function optional(schema: z.core.$ZodType): boolean {
  const definition = schema._zod.def as { type: string; innerType?: z.core.$ZodType }
  return ["optional", "nullable", "null"].includes(definition.type) || Boolean(definition.innerType && optional(definition.innerType))
}

const identifier = z.string().min(1).refine((value) => !value.includes("\0"), "SQL identifiers cannot contain a null byte")
