// Imports
import ts from "typescript"

/** Compile annotated SQL sources into one typed Query class. */
export function generate(sources: readonly string[]): string {
  // Collect imports, query declarations, and hook registrations
  let unused = false
  const imports = new Set<string>()
  const methods = [] as string[]
  const signatures = [] as string[]
  const names = new Set<string>()
  const registrations = { pre: new Map<string, string[]>(), post: new Map<string, string[]>() }
  for (const source of sources) {
    let signature = ""
    let sql = [] as string[]
    let hooks = [] as directive[]
    // Flush the preceding query when a new signature is encountered
    const flush = () => {
      if (!signature)
        return
      const method = compile(signature, sql.join("\n").trim(), hooks)
      if (names.has(method.name))
        throw new SyntaxError(`Duplicate query name "${method.name}"`)
      names.add(method.name)
      unused ||= method.unused
      methods.push(method.code)
      signatures.push(method.signature)
      // Accumulate compatible signatures for each registered hook
      for (const phase of ["pre", "post"] as const) {
        for (const [index, name] of method.hooks[phase].entries()) {
          const entries = registrations[phase].get(name) ?? []
          const tuple = `NonNullable<ReturnType<typeof Query.${method.name}>["hooks"]["${phase}"][${index}]["types"]>`
          const args = phase === "pre" ? `${tuple}[0]` : `[${tuple}[0]]`
          entries.push(`_Hook<${args}, ${tuple}[1], C>`)
          registrations[phase].set(name, entries)
        }
      }
      sql = []
      hooks = []
    }
    // Separate imports, signatures, hooks, and SQL lines
    for (const line of source.split(/\r?\n/)) {
      const directive = /^\s*--\s*@import\s+(.+?)\s*;?\s*$/.exec(line)
      const header = /^\s*--\s*([A-Za-z_$][\w$]*(?:\s*<.*>)?\s*\(.*)$/.exec(line)
      const hook = /^\s*--\s*([@#])([A-Za-z_$][\w$]*\s*\(.*)$/.exec(line)
      if (directive)
        imports.add(`import type ${directive[1].replace(/;$/, "")}`)
      else if (header) {
        flush()
        signature = header[1]
      } else if (hook) {
        if (!signature)
          throw new SyntaxError("A hook must follow a query signature")
        hooks.push({ phase: hook[1] === "#" ? "pre" : "post", text: hook[2] })
      } else if (signature)
        sql.push(line)
      else if ((line.trim()) && (!line.trimStart().startsWith("--")))
        throw new SyntaxError("SQL must follow a query signature comment")
    }
    flush()
  }
  // Resolve the supported automatic type imports
  if (!methods.length)
    throw new SyntaxError("No annotated SQL queries found")
  const code = methods.join("\n\n")
  const declarations = signatures.join("\n\n")
  const helpers = types.filter((name) => new RegExp(`\\b${name}\\b`).test(code + declarations) && ![...imports].some((line) => new RegExp(`\\b${name}\\b`).test(line)))
  const registered = registrations.pre.size + registrations.post.size > 0
  // Emit hook maps with optional context parameters
  const registry = (["pre", "post"] as const).map((phase) => {
    const entries = [...registrations[phase]].map(([name, types]) => `    \n    ${name}: ${types.join(" & ")}`).join("\n")
    return `  \n  ${phase}: ${entries ? `{\n${entries}\n  }` : "Record<never, never>"}`
  }).join("\n")
  // Assemble the module header, runtime imports, and declarations
  const generated = `// deno-coverage-ignore-file\n// deno-fmt-ignore-file\n/**\n * Generated by @libs/database/generate.\n * Do not edit.\n *\n * Last generated: ${new Date().toISOString()}\n */\n${
    unused ? "// deno-lint-ignore-file no-unused-vars\n" : ""
  }// Imports\nimport { Type as _Type } from "@libs/database"\nimport type { Query as _Query${registered ? ", Hook as _Hook, Invocation as _Invocation" : ""} } from "@libs/database"\n${helpers.length ? `import type { ${helpers.join(", ")} } from "@libs/typing"\n` : ""}${
    [...imports].join("\n")
  }\n\n\nexport default class Query {\n${code}\n}\n\n\nexport interface Hooks<${registered ? "C" : "_C"} extends Record<string, unknown> | undefined = undefined> {\n${registry}\n}\n\n${declarations}\n`
  // Compact executable code while retaining the header and SQL documentation
  return compact(generated)
}

/** Compile one TypeScript signature and its SQL body. */
function compile(signature: string, statement: string, hooks: directive[]): { name: string; code: string; signature: string; hooks: { pre: string[]; post: string[] }; unused: boolean } {
  // Validate the query signature and select collision-free internal names
  const source = parse(`function ${signature} {}`)
  const declaration = source.statements[0]
  if ((!ts.isFunctionDeclaration(declaration)) || (!declaration.name) || (!declaration.type) || (source.statements.length !== 1))
    throw new SyntaxError(`Expected a named, typed query signature: ${signature}`)
  if (!statement)
    throw new SyntaxError(`Query ${declaration.name.text} has no SQL`)
  const name = declaration.name.text
  if (["constructor", "prototype"].includes(name))
    throw new SyntaxError(`Query name "${name}" is reserved`)
  let prefix = "_database"
  while (signature.includes(prefix))
    prefix += "_"
  const identifiers = new Set<string>()
  // Collect names introduced by nested binding patterns.
  const collect = (name: ts.BindingName): void => {
    if (ts.isIdentifier(name))
      identifiers.add(name.text)
    else {
      for (const element of name.elements) {
        if (ts.isBindingElement(element))
          collect(element.name)
      }
    }
  }
  declaration.parameters.forEach((parameter) => collect(parameter.name))
  // Capture positional arguments while preserving defaults and destructuring
  const captures = [] as string[]
  const parameters = declaration.parameters.map((parameter, index) => {
    if (parameter.name.getText(source) === "this")
      throw new SyntaxError("Query signatures cannot declare a this parameter")
    const value = parameter.dotDotDotToken ? `${prefix}args.slice(${index}) as ${parameter.type!.getText(source)}` : `${prefix}args[${index}]`
    const resolved = parameter.initializer ? `${value} === undefined ? (${parameter.initializer.getText(source)}) : ${value}` : value
    const variable = ts.isIdentifier(parameter.name) ? parameter.name.text : `${prefix}${index}`
    captures.push(`const ${variable} = ${resolved}`)
    if (!ts.isIdentifier(parameter.name))
      captures.push(`const ${parameter.name.getText(source)} = ${variable}`)
    return variable
  })
  // Resolve positional, named, and context bindings to safe property accesses
  const sql = bind(statement, (expression) => {
    const positional = /^(\d+)(?=\.|\[|$)/.exec(expression)
    if (positional) {
      const index = Number(positional[1])
      if ((!Number.isInteger(index)) || (index < 0) || (index > parameters.length))
        throw new SyntaxError(`Invalid argument index in binding "${expression}"`)
      expression = (index === 0 ? `${prefix}context` : parameters[index - 1]) + expression.slice(positional[1].length)
    }
    // Reject expressions other than declared inputs and property paths
    const node = parse(`const value = ${expression}`).statements[0] as ts.VariableStatement
    const value = node.declarationList.declarations[0].initializer!
    // Validate property-only access without executing arbitrary expressions
    const validate = (value: ts.Expression): boolean => {
      if (ts.isIdentifier(value))
        return (value.text === `${prefix}context`) || identifiers.has(value.text) || parameters.includes(value.text)
      if (ts.isPropertyAccessExpression(value))
        return validate(value.expression)
      if (ts.isElementAccessExpression(value))
        return validate(value.expression) && (ts.isStringLiteral(value.argumentExpression) || ts.isNumericLiteral(value.argumentExpression) || validate(value.argumentExpression))
      return false
    }
    if ((!validate(value)) || (value.getText() !== expression))
      throw new SyntaxError(`Invalid parameter path "${expression}"`)
    if (positional && Number(positional[1]) === 0) {
      // Resolve context paths while preserving null for an absent context
      const access = (value: ts.Expression): string => {
        if (ts.isPropertyAccessExpression(value))
          return `(${access(value.expression)} as Record<PropertyKey, unknown> | null)?.[${JSON.stringify(value.name.text)}]`
        if (ts.isElementAccessExpression(value))
          return `(${access(value.expression)} as Record<PropertyKey, unknown> | null)?.[${value.argumentExpression.getText()}]`
        return `${prefix}context`
      }
      return `(${access(value)} ?? null)`
    }
    return expression
  })
  // Preserve generic parameters and the declared input tuple
  const type = declaration.type.getText(source)
  const generics = declaration.typeParameters ? `<${declaration.typeParameters.map((parameter) => parameter.getText(source)).join(", ")}>` : ""
  const arguments_ = declaration.typeParameters ? `<${declaration.typeParameters.map((parameter) => parameter.name.text).join(", ")}>` : ""
  const inputs = `Parameters<typeof _signature_${name}${arguments_}>`
  let output = type
  const transitions = { pre: [] as string[], post: [] as string[] }
  const invocations = { pre: [] as string[], post: [] as string[] }
  const names = { pre: [] as string[], post: [] as string[] }
  // Parse hook calls and propagate declared post-hook result types
  for (const { phase, text: hook } of hooks) {
    const text = `const value = ${hook}`
    const source = ts.createSourceFile("hook.ts", text, ts.ScriptTarget.Latest, true)
    const node = (source.statements[0] as ts.VariableStatement).declarationList.declarations[0].initializer!
    if ((!ts.isCallExpression(node)) || (!ts.isIdentifier(node.expression)))
      throw new SyntaxError(`Invalid ${phase}-hook ${hook}`)
    parse(`const value = ${node.getText(source)}`)
    // Accept result annotations only for post-hooks
    const tail = text.slice(node.end).trim()
    const previous = output
    if (tail) {
      if ((phase === "pre") || (!tail.startsWith(":")))
        throw new SyntaxError(`Invalid ${phase}-hook return type: ${hook}`)
      const declaration = parse(`type Output = ${tail.slice(1)}`)
      if (declaration.statements.length !== 1)
        throw new SyntaxError(`Invalid post-hook return type: ${hook}`)
      output = (declaration.statements[0] as ts.TypeAliasDeclaration).type.getText(declaration)
    }
    // Record hook arguments and type transitions for the generated registry
    transitions[phase].push(phase === "pre" ? `_Invocation<${inputs}, ${inputs}>` : `_Invocation<Awaited<${previous}>, Awaited<${output}>>`)
    invocations[phase].push(`{ name: ${JSON.stringify(node.expression.text)}, args: [${node.arguments.map((argument) => argument.getText(source)).join(", ")}] }`)
    names[phase].push(node.expression.text)
  }
  // Select row cardinality and rebuild normalized arguments
  const mode = shape(declaration.type)
  const result = mode === "array" ? `${prefix}rows` : mode === "void" ? "undefined" : mode === "nullable" ? `${prefix}rows[0] ?? null` : `${prefix}rows[0]`
  const normalized = parameters.map((parameter, index) => declaration.parameters[index].dotDotDotToken ? `...${parameter}` : parameter).join(", ")
  // Document the annotated query using PostgreSQL parameter placeholders
  const documentation = [`-- ${signature}`, ...hooks.map(({ phase, text }) => `-- ${phase === "pre" ? "#" : "@"}${text}`), sql.postgres].join("\n").replaceAll("*/", "*\\/")
  return {
    name,
    unused: [...identifiers].some((name) => !name.startsWith("_")) || (mode === "void"),
    signature: `\nfunction _signature_${name}${generics}(${declaration.parameters.map((parameter) => parameter.getText(source)).join(", ")}): void {}`,
    hooks: names,
    code: `  /**\n * \`\`\`sql\n${documentation.split("\n").map((line) => ` * ${line}`).join("\n")}\n * \`\`\`\n */\n  static ${name}${generics}(...${prefix}args: ${inputs}): _Query<Awaited<${output}>, Awaited<${type}>, ${inputs}>${
      hooks.length ? ` & { hooks: { pre: [${transitions.pre.join(", ")}]; post: [${transitions.post.join(", ")}] } }` : ""
    } {\n    ${captures.join("\n    ")}\n    return {\n      inputs: [${normalized}] as ${inputs},\n      \n      bind(inputs) { return Query.${name}${arguments_}(...inputs) },\n      hooks: { pre: [${invocations.pre.join(", ")}], post: [${
      invocations.post.join(", ")
    }] },\n      \n      async execute(${prefix}, ${prefix}context) {\n        const ${prefix}rows = await ${prefix}.prepare(${prefix}.type === _Type.SQLite ? ${JSON.stringify(sql.sqlite)} : ${JSON.stringify(sql.postgres)}).run(${sql.parameters.join(", ")})\n        ${
      mode === "one" ? `if (!${prefix}rows.length) throw new ReferenceError(${JSON.stringify(`Query ${name} returned no rows`)})` : ""
    }\n        return (${result}) as unknown as Awaited<${type}>\n      },\n    }\n  }`,
  }
}

/** Parse TypeScript with syntax diagnostics enabled. */
function parse(text: string): ts.SourceFile {
  // Report the first TypeScript syntax error before emitting code
  const source = ts.createSourceFile("query.ts", text, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS)
  const diagnostics = (source as ts.SourceFile & { parseDiagnostics: readonly ts.Diagnostic[] }).parseDiagnostics
  if (diagnostics.length)
    throw new SyntaxError(ts.flattenDiagnosticMessageText(diagnostics[0].messageText, "\n"))
  return source
}

/** Infer row cardinality from explicit array, optional, and nullable annotations. */
function shape(type: ts.TypeNode): "array" | "one" | "optional" | "nullable" | "void" {
  // Unwrap type operators and identify explicit nullable or optional results
  if ((ts.isParenthesizedTypeNode(type)) || (ts.isTypeOperatorNode(type)))
    return shape(type.type)
  if (ts.isUnionTypeNode(type)) {
    if (type.types.some((type) => type.kind === ts.SyntaxKind.UndefinedKeyword))
      return "optional"
    if (type.types.some((type) => type.kind === ts.SyntaxKind.LiteralType && (type as ts.LiteralTypeNode).literal.kind === ts.SyntaxKind.NullKeyword))
      return "nullable"
    return shape(type.types[0])
  }
  // Recognize arrays, empty results, and supported type wrappers
  if ((ts.isArrayTypeNode(type)) || ts.isTupleTypeNode(type))
    return "array"
  if ((type.kind === ts.SyntaxKind.VoidKeyword) || (type.kind === ts.SyntaxKind.UndefinedKeyword))
    return "void"
  if (ts.isTypeReferenceNode(type)) {
    const name = type.typeName.getText()
    if (["Array", "ReadonlyArray", "NonEmptyArray", "Arrayable"].includes(name))
      return "array"
    if (["Optional", "Voidable"].includes(name))
      return "optional"
    if (name === "Nullable")
      return "nullable"
    if (["Promise", "Promisable", "Awaited", "NonVoid"].includes(name) && type.typeArguments?.length)
      return shape(type.typeArguments[0])
  }
  return "one"
}

/** Replace template bindings outside SQL strings, identifiers, and comments. */
function bind(source: string, resolve: (expression: string) => string): { sqlite: string; postgres: string; parameters: string[] } {
  // Track SQL for each backend and its ordered binding expressions
  const parameters = [] as string[]
  let sqlite = ""
  let postgres = ""
  let index = 0
  // Scan SQL without interpreting bindings inside quoted or commented text
  while (index < source.length) {
    const rest = source.slice(index)
    const delimiter = /^(?:\$[A-Za-z_][\w]*\$|\$\$)/.exec(rest)?.[0]
    let end = index + 1
    // Preserve line comments and nested block comments
    if (rest.startsWith("--")) {
      const newline = source.indexOf("\n", index)
      end = newline < 0 ? source.length : newline
    } else if (rest.startsWith("/*")) {
      let depth = 1
      end = index + 2
      while ((end < source.length) && depth) {
        if (source.slice(end, end + 2) === "/*") {
          depth++
          end += 2
        } else if (source.slice(end, end + 2) === "*/") {
          depth--
          end += 2
        } else {
          end++
        }
      }
      if (depth)
        throw new SyntaxError("Unterminated SQL block comment")
    } else if (delimiter) {
      // Preserve PostgreSQL dollar-quoted strings
      const closing = source.indexOf(delimiter, index + delimiter.length)
      if (closing < 0)
        throw new SyntaxError(`Unterminated SQL dollar quote ${delimiter}`)
      end = closing + delimiter.length
    } else if (["'", '"', "`", "["].includes(source[index])) {
      // Consume SQL strings and quoted identifiers with their escape rules
      const quote = source[index] === "[" ? "]" : source[index]
      let closed = false
      const escape = (quote === "'") && /(?:^|[^\w$])[eE]$/.test(source.slice(0, index))
      while (end < source.length) {
        if (escape && source[end] === "\\") {
          end += 2
          continue
        }
        if (source[end++] === quote) {
          if (source[end] === quote)
            end++
          else {
            closed = true
            break
          }
        }
      }
      if (!closed)
        throw new SyntaxError(`Unterminated SQL quote ${source[index]}`)
    } else if (rest.startsWith("${")) {
      // Extract a binding while respecting quoted property names
      const start = index + 2
      let quote = ""
      end = start
      for (; end < source.length; end++) {
        const char = source[end]
        if (quote) {
          if (char === "\\")
            end++
          else if (char === quote)
            quote = ""
        } else if ((char === "'") || (char === '"'))
          quote = char
        else if (char === "}")
          break
      }
      if (end === source.length)
        throw new SyntaxError("Unterminated SQL parameter binding")
      // Emit backend-specific placeholders in binding order
      const expression = resolve(source.slice(start, end).trim())
      parameters.push(expression)
      sqlite += "?"
      postgres += `$${parameters.length}`
      index = end + 1
      continue
    }
    // Copy untouched SQL to both backend statements
    sqlite += source.slice(index, end)
    postgres += source.slice(index, end)
    index = end
  }
  return { sqlite, postgres, parameters }
}

const types = ["Optional", "Voidable", "Nullable", "Arrayable", "Promisable", "NonEmptyArray", "NonVoid"]

/** Compact TypeScript tokens without changing literals or automatic semicolon insertion. */
function compact(text: string): string {
  // Let the TypeScript printer insert required statement separators
  const printed = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed }).printFile(parse(text))
  const source = parse(printed)
  let output = ""
  let previous = ""
  const comments = new Set<number>()
  // Preserve file directives, the generated header, and query documentation
  const visit = (node: ts.Node): void => {
    if ((node.kind >= ts.SyntaxKind.FirstJSDocNode) && (node.kind <= ts.SyntaxKind.LastJSDocNode))
      return
    const children = node.getChildren(source)
    if (children.length) {
      children.forEach(visit)
      return
    }
    if (node.kind > ts.SyntaxKind.LastToken)
      return
    for (const comment of ts.getLeadingCommentRanges(printed, node.pos) ?? []) {
      const value = printed.slice(comment.pos, comment.end)
      if (!comments.has(comment.pos) && (value.includes("deno-") || value.includes("Generated by") || value.includes("```sql"))) {
        output += (output.endsWith("\n") || !output ? "" : "\n") + value + "\n"
        comments.add(comment.pos)
      }
    }
    const token = node.getText(source)
    if (!token)
      return
    // Separate tokens that would merge into identifiers, numbers, or operators
    if (
      !output.endsWith("\n") &&
      ((/[\p{ID_Continue}$]$/u.test(previous) && /^[\p{ID_Continue}$]/u.test(token)) || (/[+\-*/<>=!&|?%^~]$/.test(previous) && /^[+\-*/<>=!&|?%^~]/.test(token)) || (previous.endsWith("/") && /^[\p{ID_Continue}$]/u.test(token)) || (/\d$/.test(previous) && token.startsWith(".")))
    ) {
      output += " "
    }
    output += token
    previous = token
  }
  visit(source)
  return output.trim() + "\n"
}

/** A hook directive parsed from a SQL comment. */
type directive = { phase: "pre" | "post"; text: string }
