export {
  type ArrayValueType,
  type DeepMerge,
  deepMerge,
  type DeepMergeOptions,
  type ExpandRecursively,
  type MapKeyType,
  type MapValueType,
  type Merge,
  type MergeAllArrays,
  type MergeAllMaps,
  type MergeAllRecords,
  type MergeAllSets,
  type MergeRightOmitComplexes,
  type MergingStrategy,
  type ObjectXorKeys,
  type OmitComplexes,
  type PartialByType,
  type SetValueType,
} from "jsr:@std/collections@1.0.5/deep-merge"
