export {
  aggregateGroups,
  type ArrayValueType,
  associateBy,
  associateWith,
  chunk,
  type DeepMerge,
  deepMerge,
  type DeepMergeOptions,
  distinct,
  distinctBy,
  dropLastWhile,
  dropWhile,
  type ExpandRecursively,
  filterEntries,
  filterKeys,
  filterValues,
  findSingle,
  firstNotNullishOf,
  includesValue,
  intersect,
  invert,
  invertBy,
  type InvertByResult,
  type InvertResult,
  joinToString,
  type JoinToStringOptions,
  mapEntries,
  mapKeys,
  type MapKeyType,
  mapNotNullish,
  mapValues,
  type MapValueType,
  maxBy,
  maxOf,
  maxWith,
  type Merge,
  type MergeAllArrays,
  type MergeAllMaps,
  type MergeAllRecords,
  type MergeAllSets,
  type MergeRightOmitComplexes,
  type MergingStrategy,
  minBy,
  minOf,
  minWith,
  type ObjectXorKeys,
  omit,
  type OmitComplexes,
  type Order,
  type PartialByType,
  partition,
  partitionEntries,
  permutations,
  pick,
  reduceGroups,
  runningReduce,
  sample,
  type SetValueType,
  slidingWindows,
  type SlidingWindowsOptions,
  sortBy,
  type SortByOptions,
  sumOf,
  takeLastWhile,
  takeWhile,
  union,
  unzip,
  withoutAll,
  zip,
} from "jsr:@std/collections@1.0.4"
