// deno-lint-ignore-file no-console
import { parseArgs } from "@std/cli"
import { gray, green } from "@std/fmt/colors"
import { expandGlob } from "@std/fs"
// deno-lint-ignore no-import-prefix
const { default: hljs } = await import("npm:highlight.js@11")

const args = parseArgs(Deno.args, { string: ["root", "language"], boolean: ["help"], default: { root: "coverage", language: "ts" } })
if (args.help) {
  console.error(`Usage: deno run --allow-read --allow-write jsr:@libs/toolbox/scripts/highlight-coverage`)
  console.error(``)
  console.error(`Enhances HTML coverage reports generated by "deno coverage --html" with matcha.css styling and highlight.js syntax highlighting.`)
  console.error(``)
  console.error(`Options:`)
  console.error(`  --root=DIR       Root directory to search for html coverage reports (default: coverage)`)
  console.error(`  --language=LANG  Language used for syntax highlighting (default: ts)`)
  console.error(`  --help           Show this help message`)
  console.error(``)
  Deno.exit(2)
}

const stylesheets = ["@root", "@syntax-highlighting", "@istanbul-coverage"].map((name) => `<link rel='stylesheet' href='https://matcha.mizu.sh/styles/${name}/mod.css'>`).join("")
const entities = { "&lt;": "<", "&gt;": ">", "&quot;": '"', "&#39;": "'", "&amp;": "&" }

for await (const { path } of expandGlob("**/*.html", { root: args.root })) {
  let html = await Deno.readTextFile(path)
  if (!/<title>Coverage report/.test(html)) {
    console.error(gray(`∅ ${path}`))
    continue
  }
  if (!html.includes("matcha.mizu.sh"))
    html = html.replace("</head>", `${stylesheets}</head>`)
  html = html.replace(/<pre class='prettyprint'>([\s\S]*?)<\/pre>/g, (_, code: string) => {
    const text = Object.entries(entities).reduce((text, [entity, character]) => text.replaceAll(entity, character), code.replace(/<[^>]*>/g, ""))
    return `<pre class='prettyprint hljs' data-highlighted='true'>${hljs.highlight(text, { language: args.language }).value}</pre>`
  })
  await Deno.writeTextFile(path, html)
  console.error(green(`✓ ${path}`))
}
