// Imports
import { Renderer } from "../renderer.ts"

/** Renderer instance. */
const renderer = new Renderer({ highlighting: true })

/**
 * Renders a markdown expression suitable for SVG (raw HTML is escaped so the output only contains markup generated by the renderer itself).
 */
export function markdown(text: string): string {
  return renderer.render(text)
}
