// Generated by @libs/database/generate. Do not edit.
// deno-lint-ignore-file no-unused-vars
// Imports
import { Type as _Type } from "@libs/database"
import type { Callback as _Callback, Invocation as _Invocation, Query as _Query } from "@libs/database"
import type { Nullable } from "@libs/typing"
import type { Greeting, User } from "./types.ts"

/** Typed deferred SQL queries. */
export default class Query {
  /** Execute hello. */
  static hello(..._databaseargs: Parameters<typeof _signature_hello>): _Query<Awaited<Greeting>, Awaited<Greeting>> {
    const name = _databaseargs[0]
    return {
      callbacks: [],
      /** Run the query on the selected database. */
      async execute(_database) {
        const _databaserows = await _database.prepare(_database.type === _Type.SQLite ? "SELECT 'Hello, ' || ? AS message;" : "SELECT 'Hello, ' || $1 AS message;").run(name)
        if (!_databaserows.length)
          throw new RangeError("Query hello returned no rows")
        return (_databaserows[0]) as unknown as Awaited<Greeting>
      },
    }
  }

  /** Execute helloText. */
  static helloText(..._databaseargs: Parameters<typeof _signature_helloText>): _Query<Awaited<string>, Awaited<Greeting>> & { callbacks: [_Invocation<Awaited<Greeting>, Awaited<string>>] } {
    const name = _databaseargs[0]
    return {
      callbacks: [{ name: "message", args: [] }],
      /** Run the query on the selected database. */
      async execute(_database) {
        const _databaserows = await _database.prepare(_database.type === _Type.SQLite ? "SELECT 'Hello, ' || ? AS message;" : "SELECT 'Hello, ' || $1 AS message;").run(name)
        if (!_databaserows.length)
          throw new RangeError("Query helloText returned no rows")
        return (_databaserows[0]) as unknown as Awaited<Greeting>
      },
    }
  }

  /** Execute users. */
  static users(..._databaseargs: Parameters<typeof _signature_users>): _Query<Awaited<User[]>, Awaited<User[]>> {
    const domain = _databaseargs[0] === undefined ? ("example.org") : _databaseargs[0]
    return {
      callbacks: [],
      /** Run the query on the selected database. */
      async execute(_database) {
        const _databaserows = await _database.prepare(_database.type === _Type.SQLite ? "SELECT * FROM users WHERE domain=? ORDER BY id;" : "SELECT * FROM users WHERE domain=$1 ORDER BY id;").run(domain)

        return _databaserows as unknown as Awaited<User[]>
      },
    }
  }

  /** Execute user. */
  static user(..._databaseargs: Parameters<typeof _signature_user>): _Query<Awaited<Nullable<User>>, Awaited<Nullable<User>>> {
    const id = _databaseargs[0]
    return {
      callbacks: [],
      /** Run the query on the selected database. */
      async execute(_database) {
        const _databaserows = await _database.prepare(_database.type === _Type.SQLite ? "SELECT * FROM users WHERE id=?;" : "SELECT * FROM users WHERE id=$1;").run(id)

        return (_databaserows[0] ?? null) as unknown as Awaited<Nullable<User>>
      },
    }
  }

  /** Execute requiredUser. */
  static requiredUser(..._databaseargs: Parameters<typeof _signature_requiredUser>): _Query<Awaited<User>, Awaited<User>> {
    const _database0 = _databaseargs[0]
    const { id: key } = _database0
    return {
      callbacks: [],
      /** Run the query on the selected database. */
      async execute(_database) {
        const _databaserows = await _database.prepare(_database.type === _Type.SQLite ? "SELECT * FROM users WHERE id=?;" : "SELECT * FROM users WHERE id=$1;").run(key)
        if (!_databaserows.length)
          throw new RangeError("Query requiredUser returned no rows")
        return (_databaserows[0]) as unknown as Awaited<User>
      },
    }
  }

  /** Execute deleteUser. */
  static deleteUser(..._databaseargs: Parameters<typeof _signature_deleteUser>): _Query<Awaited<string>, Awaited<User>> & { callbacks: [_Invocation<Awaited<User>, Awaited<User>>, _Invocation<Awaited<User>, Awaited<string>>] } {
    const id = _databaseargs[0]
    return {
      callbacks: [{ name: "audit", args: ["USER_DELETE"] }, { name: "identifier", args: [] }],
      /** Run the query on the selected database. */
      async execute(_database) {
        const _databaserows = await _database.prepare(_database.type === _Type.SQLite ? "DELETE FROM users WHERE id=? RETURNING *;" : "DELETE FROM users WHERE id=$1 RETURNING *;").run(id)
        if (!_databaserows.length)
          throw new RangeError("Query deleteUser returned no rows")
        return (_databaserows[0]) as unknown as Awaited<User>
      },
    }
  }

  /** Execute recordAudit. */
  static recordAudit(..._databaseargs: Parameters<typeof _signature_recordAudit>): _Query<Awaited<void>, Awaited<void>> {
    const id = _databaseargs[0]
    const event = _databaseargs[1]
    return {
      callbacks: [],
      /** Run the query on the selected database. */
      async execute(_database) {
        const _databaserows = await _database.prepare(_database.type === _Type.SQLite ? "INSERT INTO audit(user_id, event) VALUES (?, ?);" : "INSERT INTO audit(user_id, event) VALUES ($1, $2);").run(id, event)

        return undefined as unknown as Awaited<void>
      },
    }
  }

  /** Execute events. */
  static events(..._databaseargs: Parameters<typeof _signature_events>): _Query<Awaited<{ user_id: string; event: string }[]>, Awaited<{ user_id: string; event: string }[]>> {
    return {
      callbacks: [],
      /** Run the query on the selected database. */
      async execute(_database) {
        const _databaserows = await _database.prepare(_database.type === _Type.SQLite ? "SELECT * FROM audit ORDER BY user_id;" : "SELECT * FROM audit ORDER BY user_id;").run()

        return _databaserows as unknown as Awaited<{ user_id: string; event: string }[]>
      },
    }
  }
}

/** Registered callback signatures derived from SQL result declarations. */
export interface Callbacks {
  /** Post-callback for message. */
  message: _Callback<NonNullable<ReturnType<typeof Query.helloText>["callbacks"][0]["types"]>[0], unknown[], NonNullable<ReturnType<typeof Query.helloText>["callbacks"][0]["types"]>[1]>
  /** Post-callback for audit. */
  audit: _Callback<NonNullable<ReturnType<typeof Query.deleteUser>["callbacks"][0]["types"]>[0], unknown[], NonNullable<ReturnType<typeof Query.deleteUser>["callbacks"][0]["types"]>[1]>
  /** Post-callback for identifier. */
  identifier: _Callback<NonNullable<ReturnType<typeof Query.deleteUser>["callbacks"][1]["types"]>[0], unknown[], NonNullable<ReturnType<typeof Query.deleteUser>["callbacks"][1]["types"]>[1]>
}

/** Preserve the source parameter signature for type inference. */
function _signature_hello(name: string): void {}

/** Preserve the source parameter signature for type inference. */
function _signature_helloText(name: string): void {}

/** Preserve the source parameter signature for type inference. */
function _signature_users(domain = "example.org"): void {}

/** Preserve the source parameter signature for type inference. */
function _signature_user(id: string): void {}

/** Preserve the source parameter signature for type inference. */
function _signature_requiredUser({ id: key }: { id: string }): void {}

/** Preserve the source parameter signature for type inference. */
function _signature_deleteUser(id: string): void {}

/** Preserve the source parameter signature for type inference. */
function _signature_recordAudit(id: string, event: string): void {}

/** Preserve the source parameter signature for type inference. */
function _signature_events(): void {}
